language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test_xunit # zamiana make test na make test_xunit
  - make lint
#after_success:
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: fathomless-ridge-17643 # nazwa naszej aplikacji
  api_key: ${HEROKU_API_KEY} # zmienna bedzie pobierana z travisa
  # zakladka settings na travis dodajemy zmienna HEROKU_API_KEY
  # wartosc HEROKU_API_KEY jest wynikiem komendy w cdm "heroku auth:token"
